compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "blog"
database_id = "01a05c63-1770-4c65-b044-d4a806ecbc1f"
